// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for `src/stockfish.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class StockfishChessEngineBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StockfishChessEngineBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  StockfishChessEngineBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void stockfish_init() {
    return _stockfish_init();
  }

  late final _stockfish_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stockfish_init');
  late final _stockfish_init = _stockfish_initPtr.asFunction<void Function()>();

  void stockfish_release() {
    return _stockfish_release();
  }

  late final _stockfish_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stockfish_release');
  late final _stockfish_release =
      _stockfish_releasePtr.asFunction<void Function()>();

  void stockfish_process_command(
    ffi.Pointer<ffi.Char> command,
  ) {
    return _stockfish_process_command(
      command,
    );
  }

  late final _stockfish_process_commandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'stockfish_process_command');
  late final _stockfish_process_command = _stockfish_process_commandPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> stockfish_stdout_read() {
    return _stockfish_stdout_read();
  }

  late final _stockfish_stdout_readPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'stockfish_stdout_read');
  late final _stockfish_stdout_read =
      _stockfish_stdout_readPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}
